server:
  port: 9002
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
     defaultZone: http://localhost:8888/eureka/
spring:
  application:
    name: consumer
  rabbitmq:
    host: 172.16.86.6
    port: 5672
    username: sty1
    password: sty
  cloud:
    config:
      profile: prod
      uri: http://localhost:9006/