server:
  port: 9002
spring:
  application:
    name: consumer
  rabbitmq:
    host: 172.16.86.6
    port: 5672
    username: sty1
    password: sty
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file: D:\develop\java\ide_home\log\consumer.log